version: "3"

services:
  next:
    container_name: next
    build:
      context: ./next
      dockerfile: dev.Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./next/src:/app/src
      - ./next/public:/app/public
      - ./next/components:/app/components
      - ./next/locales:/app/locales
    ports:
      - 127.0.0.1:3000:3000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m" 
        compress: "true"
    depends_on:
      - mongodb
    networks:
      - next

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:7.0-ubi8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-mongo} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-mongoSuperSecretPass}
    volumes:
      - mongodb-data:/data/db
    ports:
      - 127.0.0.1:27017:27017
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m" 
        compress: "true"
    networks:
      - next

networks:
  next:

volumes: 
  mongodb-data:
