// import { Metadata } from "next";
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";
import { Exo_2 } from "next/font/google";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import Head from "next/head";
import styles from "./components/Main/Hero/hero.module.scss";
import "@/app/styles/index.scss";
import TranslationsProvider from "../../../components/TranslationsProvider";
import initTranslations from "../i18n";

import { getServerSession } from "next-auth";
import SessionProvider from "../SessionProvider";
import ButtonScrollTop from "./components/Button/ButtonScrollTop";

import AuthManager from "../AuthManager";
import Link from "next/link";
import Translator from "./components/translator/Translator";

const exo = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "Peei",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params: { locale } }) {
  const i18nNamespaces = ["home", "navbar", "financial", "translation"];

  const { resources } = await initTranslations(locale, i18nNamespaces);
  const session = await getServerSession();

  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}
    >
      <html lang={locale} dir={dir(locale)}>
        <head>
          <meta
            name="google-site-verification"
            content="3fjcZy_xpuWteahNsjhd2ZR1_5G71223Oi21X-Z74_8"
          />
        </head>
        <body className={exo.className} suppressHydrationWarning={true}>
          <SessionProvider session={session}>
            <AuthManager />
            <div className="wrapper">
              <Header locale={locale} />
              <main>{children}</main>
              {/* Button scroll top */}
              <Link
                href="https://dsns.gov.ua/uk/abetka-bezpeki/diyi-naselennya-v-umovax-nadzvicainix-situacii-vojennogo-xarakteru"
                target="_blank"
                rel="noreferrer"
                className={styles.linkSecurity}
              >
                <Translator>safetyRulesDuringMartialLaw</Translator>
              </Link>
              <ButtonScrollTop
                nameSvg="UpArrow"
                fill="#0d490d"
                fillHovered="#fffefe"
              />

              <Footer locale={locale} />
            </div>
            <div id="modal-root"></div>
          </SessionProvider>
        </body>
      </html>
    </TranslationsProvider>
  );
}
