// import { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import { dir } from "i18next";
import i18nConfig from "@/i18nConfig";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

import "@/app/styles/index.scss";
import TranslationsProvider from "../../../components/TranslationsProvider";
import initTranslations from "../i18n";

import { getServerSession } from "next-auth";
import SessionProvider from "../SessionProvider";

const exo = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "Peei",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params: { locale } }) {
  const i18nNamespaces = ["home", "navbar", "financial", "translation"];

  const { resources } = await initTranslations(locale, i18nNamespaces);
  const session = await getServerSession();
  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}
    >
      <html lang={locale} dir={dir(locale)}>
        <body className={exo.className} suppressHydrationWarning={true}>
          <SessionProvider session={session}>
            <div className="wrapper">
              <Header locale={locale} />
              <main>{children}</main>
              <Footer locale={locale} />
            </div>
            <div id="modal-root"></div>
          </SessionProvider>
        </body>
      </html>
    </TranslationsProvider>
  );
}
