import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";

import Header from "./components/Header/Header";
import Footer from "./components/Footer";

import "@/app/styles/index.scss";

const exo = Exo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ГО",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <div className="wrapper">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
